"""
Create 10 dummy bilty (TransportBill) entries with full data
Run: python create_dummy_bilty.py
"""
from app import app, db
from models import TransportBill, Tenant, Location, DeliveryType, Vehicle
from datetime import datetime, timedelta
import json

def create_dummy_bilty():
    with app.app_context():
        # Get existing data
        tenant = Tenant.query.first()
        if not tenant:
            print("No tenant found. Please run init_db.py first.")
            return

        locations = Location.query.filter_by(tenant_id=tenant.id).all()
        delivery_types = DeliveryType.query.filter_by(tenant_id=tenant.id).all()
        vehicles = Vehicle.query.filter_by(tenant_id=tenant.id).all()

        if not locations or not delivery_types or not vehicles:
            print("Missing required data (locations, delivery types, or vehicles). Please run init_db.py first.")
            return

        # Sample data for bilty entries
        sample_data = [
            {
                "gr_number": "GR-2024-001",
                "challan_number": "CH-001",
                "party_information": "ABC Trading Co.",
                "consignor_name": "ABC Trading Co.",
                "consignor_address": "123 Industrial Area, Mumbai",
                "consignor_gstin": "27ABCDE1234F1Z5",
                "consignor_mobile": "9876543210",
                "consignor_email": "abc@trading.com",
                "consignee_name": "XYZ Retailers",
                "consignee_address": "456 Market Area, Delhi",
                "consignee_gstin": "07FGHIJ5678K2L9",
                "consignee_mobile": "9876543211",
                "consignee_email": "xyz@retail.com",
                "pickup_point": "Mumbai Warehouse",
                "pickup_city": "Mumbai",
                "pickup_state": "Maharashtra",
                "pickup_pincode": "400001",
                "delivery_location": "Delhi Warehouse",
                "delivery_city": "Delhi",
                "delivery_state": "Delhi",
                "delivery_pincode": "110001",
                "article_description": "Electronics - 50 TV Sets",
                "number_of_packages": 50,
                "actual_weight": 2500.5,
                "charged_weight": 2800.0,
                "material_value": 1500000.0,
                "declared_value": 1500000.0,
                "basic_freight": 25000.0,
                "loading_charge": 500.0,
                "unloading_charge": 500.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 4500.0,
                "taxable_amount": 25000.0,
                "freight_payment_mode": "to_pay",
                "payment_status": "pending",
                "current_shipment_status": "in_transit",
                "driver_name": "Rajesh Kumar",
                "driver_mobile": "8888888888",
                "driver_license": "DL123456789",
                "helper_name": "Suresh Singh",
                "trip_number": "TRIP-001",
                "route_code": "RT-MUM-DEL",
                "route_name": "Mumbai-Delhi Route",
                "origin": "Mumbai",
                "destination": "Delhi",
                "via_route": "Mumbai-Pune-Nagpur-Delhi",
                "freight_collected_from": "Consignee",
                "advance_amount": 5000.0,
                "balance_amount": 20000.0,
                "freight_due": 29500.0,
                "paid_amount": 5000.0,
                "receipt_number": "REC-001",
                "credit_party": "XYZ Retailers",
                "dispatch_datetime": datetime.now().isoformat(),
                "dispatch_from_branch": "Mumbai Branch",
                "expected_transit_time": "48 hours",
                "tracking_number": "TRK-001-2024",
                "created_by": "admin",
                "remarks": "Fragile items - handle with care"
            },
            {
                "gr_number": "GR-2024-002",
                "challan_number": "CH-002",
                "party_information": "PQR Industries",
                "consignor_name": "PQR Industries",
                "consignor_address": "789 Sector 18, Noida",
                "consignor_gstin": "09KLMNO3456P3Q7",
                "consignor_mobile": "9876543212",
                "consignor_email": "pqr@industries.com",
                "consignee_name": "LMN Distributors",
                "consignee_address": "321 Industrial Estate, Pune",
                "consignee_gstin": "27RSTUV6789W4X1",
                "consignee_mobile": "9876543213",
                "consignee_email": "lmn@dist.com",
                "pickup_point": "Noida Factory",
                "pickup_city": "Noida",
                "pickup_state": "Uttar Pradesh",
                "pickup_pincode": "201301",
                "delivery_location": "Pune Hub",
                "delivery_city": "Pune",
                "delivery_state": "Maharashtra",
                "delivery_pincode": "411001",
                "article_description": "Steel Pipes - 100 bundles",
                "number_of_packages": 100,
                "actual_weight": 5000.0,
                "charged_weight": 5500.0,
                "material_value": 500000.0,
                "declared_value": 500000.0,
                "basic_freight": 15000.0,
                "loading_charge": 1000.0,
                "unloading_charge": 1000.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 2700.0,
                "taxable_amount": 15000.0,
                "freight_payment_mode": "paid",
                "payment_status": "paid",
                "current_shipment_status": "delivered",
                "driver_name": "Mohan Singh",
                "driver_mobile": "8777777777",
                "driver_license": "UP987654321",
                "helper_name": "Ramesh Gupta",
                "trip_number": "TRIP-002",
                "route_code": "RT-NOI-PUN",
                "route_name": "Noida-Pune Route",
                "origin": "Noida",
                "destination": "Pune",
                "via_route": "Noida-Delhi-Jaipur-Pune",
                "freight_collected_from": "Consignor",
                "advance_amount": 0.0,
                "balance_amount": 0.0,
                "freight_due": 0.0,
                "paid_amount": 18700.0,
                "receipt_number": "REC-002",
                "credit_party": "",
                "dispatch_datetime": (datetime.now() - timedelta(days=2)).isoformat(),
                "dispatch_from_branch": "Noida Branch",
                "expected_transit_time": "72 hours",
                "actual_transit_time": "65 hours",
                "tracking_number": "TRK-002-2024",
                "delivered_datetime": (datetime.now() - timedelta(hours=5)).isoformat(),
                "delivered_by": "Security Guard",
                "received_by_name": "Amit Sharma",
                "received_by_signature": "Amit S.",
                "seal_number": "SL-002",
                "pod_number": "POD-002",
                "created_by": "admin",
                "remarks": "Heavy load - special handling required"
            },
            {
                "gr_number": "GR-2024-003",
                "challan_number": "CH-003",
                "party_information": "DEF Exports",
                "consignor_name": "DEF Exports",
                "consignor_address": "567 Export Zone, Chennai",
                "consignor_gstin": "33YZABCD9012E3F4",
                "consignor_mobile": "9876543214",
                "consignor_email": "def@exports.com",
                "consignee_name": "GHI Imports",
                "consignee_address": "890 Port Area, Bangalore",
                "consignee_gstin": "29GHIJKL3456M7N8",
                "consignee_mobile": "9876543215",
                "consignee_email": "ghi@imports.com",
                "pickup_point": "Chennai Port",
                "pickup_city": "Chennai",
                "pickup_state": "Tamil Nadu",
                "pickup_pincode": "600001",
                "delivery_location": "Bangalore Airport",
                "delivery_city": "Bangalore",
                "delivery_state": "Karnataka",
                "delivery_pincode": "560001",
                "article_description": "Textile Fabrics - 200 rolls",
                "number_of_packages": 200,
                "actual_weight": 3000.0,
                "charged_weight": 3200.0,
                "material_value": 800000.0,
                "declared_value": 800000.0,
                "basic_freight": 18000.0,
                "loading_charge": 800.0,
                "unloading_charge": 800.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 3240.0,
                "taxable_amount": 18000.0,
                "freight_payment_mode": "to_pay",
                "payment_status": "pending",
                "current_shipment_status": "in_transit",
                "driver_name": "Karthik Rajan",
                "driver_mobile": "8666666666",
                "driver_license": "TN123456789",
                "helper_name": "Suresh Kumar",
                "trip_number": "TRIP-003",
                "route_code": "RT-CHE-BAN",
                "route_name": "Chennai-Bangalore Route",
                "origin": "Chennai",
                "destination": "Bangalore",
                "via_route": "Chennai-Vellore-Bangalore",
                "freight_collected_from": "Consignee",
                "advance_amount": 8000.0,
                "balance_amount": 10000.0,
                "freight_due": 22840.0,
                "paid_amount": 8000.0,
                "receipt_number": "REC-003",
                "credit_party": "GHI Imports",
                "dispatch_datetime": datetime.now().isoformat(),
                "dispatch_from_branch": "Chennai Branch",
                "expected_transit_time": "24 hours",
                "tracking_number": "TRK-003-2024",
                "created_by": "admin",
                "remarks": "Temperature controlled - 20°C required"
            },
            {
                "gr_number": "GR-2024-004",
                "challan_number": "CH-004",
                "party_information": "JKL Logistics",
                "consignor_name": "JKL Logistics",
                "consignor_address": "234 Logistics Park, Hyderabad",
                "consignor_gstin": "36MNOPQR7890S1T2",
                "consignor_mobile": "9876543216",
                "consignor_email": "jkl@logistics.com",
                "consignee_name": "MNO Transport",
                "consignee_address": "678 Transport Hub, Jaipur",
                "consignee_gstin": "08STUVWX9012Y3Z4",
                "consignee_mobile": "9876543217",
                "consignee_email": "mno@transport.com",
                "pickup_point": "Hyderabad Depot",
                "pickup_city": "Hyderabad",
                "pickup_state": "Telangana",
                "pickup_pincode": "500001",
                "delivery_location": "Jaipur Warehouse",
                "delivery_city": "Jaipur",
                "delivery_state": "Rajasthan",
                "delivery_pincode": "302001",
                "article_description": "Chemical Drums - 80 drums",
                "number_of_packages": 80,
                "actual_weight": 4000.0,
                "charged_weight": 4400.0,
                "material_value": 1200000.0,
                "declared_value": 1200000.0,
                "insurance_required": True,
                "insurance_value": 1200000.0,
                "basic_freight": 22000.0,
                "loading_charge": 1200.0,
                "unloading_charge": 1200.0,
                "insurance_charge": 500.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 4140.0,
                "taxable_amount": 23000.0,
                "freight_payment_mode": "to_pay",
                "payment_status": "partial",
                "current_shipment_status": "in_transit",
                "driver_name": "Venkat Reddy",
                "driver_mobile": "8555555555",
                "driver_license": "TS123456789",
                "helper_name": "Ravi Teja",
                "trip_number": "TRIP-004",
                "route_code": "RT-HYD-JAI",
                "route_name": "Hyderabad-Jaipur Route",
                "origin": "Hyderabad",
                "destination": "Jaipur",
                "via_route": "Hyderabad-Nagpur-Jaipur",
                "freight_collected_from": "Consignee",
                "advance_amount": 10000.0,
                "balance_amount": 13000.0,
                "freight_due": 29040.0,
                "paid_amount": 10000.0,
                "receipt_number": "REC-004",
                "credit_party": "MNO Transport",
                "dispatch_datetime": datetime.now().isoformat(),
                "dispatch_from_branch": "Hyderabad Branch",
                "expected_transit_time": "36 hours",
                "tracking_number": "TRK-004-2024",
                "created_by": "admin",
                "remarks": "Hazardous material - safety protocols required"
            },
            {
                "gr_number": "GR-2024-005",
                "challan_number": "CH-005",
                "party_information": "NOP Pharmaceuticals",
                "consignor_name": "NOP Pharmaceuticals",
                "consignor_address": "901 Pharma Zone, Ahmedabad",
                "consignor_gstin": "24ABCDEFG1234H5I6",
                "consignor_mobile": "9876543218",
                "consignor_email": "nop@pharma.com",
                "consignee_name": "QRS Medical Stores",
                "consignee_address": "345 Medical Area, Kolkata",
                "consignee_gstin": "19JKLMNO5678P9Q0",
                "consignee_mobile": "9876543219",
                "consignee_email": "qrs@medical.com",
                "pickup_point": "Ahmedabad Factory",
                "pickup_city": "Ahmedabad",
                "pickup_state": "Gujarat",
                "pickup_pincode": "380001",
                "delivery_location": "Kolkata Distribution Center",
                "delivery_city": "Kolkata",
                "delivery_state": "West Bengal",
                "delivery_pincode": "700001",
                "article_description": "Medicines - 500 cartons",
                "number_of_packages": 500,
                "actual_weight": 1500.0,
                "charged_weight": 1650.0,
                "material_value": 2500000.0,
                "declared_value": 2500000.0,
                "insurance_required": True,
                "insurance_value": 2500000.0,
                "basic_freight": 20000.0,
                "loading_charge": 600.0,
                "unloading_charge": 600.0,
                "insurance_charge": 1000.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 3780.0,
                "taxable_amount": 21000.0,
                "freight_payment_mode": "paid",
                "payment_status": "paid",
                "current_shipment_status": "delivered",
                "driver_name": "Amit Patel",
                "driver_mobile": "8444444444",
                "driver_license": "GJ123456789",
                "helper_name": "Dinesh Shah",
                "trip_number": "TRIP-005",
                "route_code": "RT-AMD-KOL",
                "route_name": "Ahmedabad-Kolkata Route",
                "origin": "Ahmedabad",
                "destination": "Kolkata",
                "via_route": "Ahmedabad-Mumbai-Kolkata",
                "freight_collected_from": "Consignor",
                "advance_amount": 0.0,
                "balance_amount": 0.0,
                "freight_due": 0.0,
                "paid_amount": 25980.0,
                "receipt_number": "REC-005",
                "credit_party": "",
                "dispatch_datetime": (datetime.now() - timedelta(days=3)).isoformat(),
                "dispatch_from_branch": "Ahmedabad Branch",
                "expected_transit_time": "96 hours",
                "actual_transit_time": "90 hours",
                "tracking_number": "TRK-005-2024",
                "delivered_datetime": (datetime.now() - timedelta(hours=6)).isoformat(),
                "delivered_by": "Warehouse Manager",
                "received_by_name": "Rahul Das",
                "received_by_signature": "Rahul D.",
                "seal_number": "SL-005",
                "pod_number": "POD-005",
                "created_by": "admin",
                "remarks": "Temperature controlled - 15°C required, priority delivery"
            },
            {
                "gr_number": "GR-2024-006",
                "challan_number": "CH-006",
                "party_information": "TUV Construction",
                "consignor_name": "TUV Construction",
                "consignor_address": "567 Construction Site, Lucknow",
                "consignor_gstin": "09RSTUVW9012X3Y4",
                "consignor_mobile": "9876543220",
                "consignor_email": "tuv@construction.com",
                "consignee_name": "WXY Builders",
                "consignee_address": "890 Building Site, Patna",
                "consignee_gstin": "10ZABCDE3456F7G8",
                "consignee_mobile": "9876543221",
                "consignee_email": "wxy@builders.com",
                "pickup_point": "Lucknow Depot",
                "pickup_city": "Lucknow",
                "pickup_state": "Uttar Pradesh",
                "pickup_pincode": "226001",
                "delivery_location": "Patna Construction Site",
                "delivery_city": "Patna",
                "delivery_state": "Bihar",
                "delivery_pincode": "800001",
                "article_description": "Cement Bags - 1000 bags",
                "number_of_packages": 1000,
                "actual_weight": 50000.0,
                "charged_weight": 55000.0,
                "material_value": 400000.0,
                "declared_value": 400000.0,
                "basic_freight": 35000.0,
                "loading_charge": 2000.0,
                "unloading_charge": 2000.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 6300.0,
                "taxable_amount": 35000.0,
                "freight_payment_mode": "to_pay",
                "payment_status": "pending",
                "current_shipment_status": "in_transit",
                "driver_name": "Sanjay Singh",
                "driver_mobile": "8333333333",
                "driver_license": "UP234567890",
                "helper_name": "Vijay Kumar",
                "trip_number": "TRIP-006",
                "route_code": "RT-LUC-PAT",
                "route_name": "Lucknow-Patna Route",
                "origin": "Lucknow",
                "destination": "Patna",
                "via_route": "Lucknow-Varanasi-Patna",
                "freight_collected_from": "Consignee",
                "advance_amount": 15000.0,
                "balance_amount": 20000.0,
                "freight_due": 45300.0,
                "paid_amount": 15000.0,
                "receipt_number": "REC-006",
                "credit_party": "WXY Builders",
                "dispatch_datetime": datetime.now().isoformat(),
                "dispatch_from_branch": "Lucknow Branch",
                "expected_transit_time": "24 hours",
                "tracking_number": "TRK-006-2024",
                "created_by": "admin",
                "remarks": "Heavy load - multiple vehicles required"
            },
            {
                "gr_number": "GR-2024-007",
                "challan_number": "CH-007",
                "party_information": "ZAB Electronics",
                "consignor_name": "ZAB Electronics",
                "consignor_address": "123 Electronics Park, Gurgaon",
                "consignor_gstin": "06HIJKLM7890N1O2",
                "consignor_mobile": "9876543222",
                "consignor_email": "zab@electronics.com",
                "consignee_name": "CDE Retail",
                "consignee_address": "456 Retail Street, Chandigarh",
                "consignee_gstin": "03PQRSTU9012V3W4",
                "consignee_mobile": "9876543223",
                "consignee_email": "cde@retail.com",
                "pickup_point": "Gurgaon Warehouse",
                "pickup_city": "Gurgaon",
                "pickup_state": "Haryana",
                "pickup_pincode": "122001",
                "delivery_location": "Chandigarh Store",
                "delivery_city": "Chandigarh",
                "delivery_state": "Chandigarh",
                "delivery_pincode": "160001",
                "article_description": "Laptops - 100 units",
                "number_of_packages": 100,
                "actual_weight": 500.0,
                "charged_weight": 550.0,
                "material_value": 3000000.0,
                "declared_value": 3000000.0,
                "insurance_required": True,
                "insurance_value": 3000000.0,
                "basic_freight": 8000.0,
                "loading_charge": 300.0,
                "unloading_charge": 300.0,
                "insurance_charge": 2000.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 1440.0,
                "taxable_amount": 8000.0,
                "freight_payment_mode": "paid",
                "payment_status": "paid",
                "current_shipment_status": "delivered",
                "driver_name": "Rajinder Singh",
                "driver_mobile": "8222222222",
                "driver_license": "HR123456789",
                "helper_name": "Gurpreet Singh",
                "trip_number": "TRIP-007",
                "route_code": "RT-GUR-CHA",
                "route_name": "Gurgaon-Chandigarh Route",
                "origin": "Gurgaon",
                "destination": "Chandigarh",
                "via_route": "Gurgaon-Delhi-Chandigarh",
                "freight_collected_from": "Consignor",
                "advance_amount": 0.0,
                "balance_amount": 0.0,
                "freight_due": 0.0,
                "paid_amount": 12040.0,
                "receipt_number": "REC-007",
                "credit_party": "",
                "dispatch_datetime": (datetime.now() - timedelta(days=1)).isoformat(),
                "dispatch_from_branch": "Gurgaon Branch",
                "expected_transit_time": "12 hours",
                "actual_transit_time": "10 hours",
                "tracking_number": "TRK-007-2024",
                "delivered_datetime": (datetime.now() - timedelta(hours=14)).isoformat(),
                "delivered_by": "Store Manager",
                "received_by_name": "Vikram Sharma",
                "received_by_signature": "Vikram S.",
                "seal_number": "SL-007",
                "pod_number": "POD-007",
                "created_by": "admin",
                "remarks": "High value items - priority delivery, GPS tracking enabled"
            },
            {
                "gr_number": "GR-2024-008",
                "challan_number": "CH-008",
                "party_information": "EFG Foods",
                "consignor_name": "EFG Foods",
                "consignor_address": "789 Food Park, Indore",
                "consignor_gstin": "23WXYZAB1234C5D6",
                "consignor_mobile": "9876543224",
                "consignor_email": "efg@foods.com",
                "consignee_name": "HIJ Supermarket",
                "consignee_address": "012 Supermarket Road, Bhopal",
                "consignee_gstin": "23DEFGH5678I9J0",
                "consignee_mobile": "9876543225",
                "consignee_email": "hij@supermarket.com",
                "pickup_point": "Indore Factory",
                "pickup_city": "Indore",
                "pickup_state": "Madhya Pradesh",
                "pickup_pincode": "452001",
                "delivery_location": "Bhopal Store",
                "delivery_city": "Bhopal",
                "delivery_state": "Madhya Pradesh",
                "delivery_pincode": "462001",
                "article_description": "Food Grains - 200 bags",
                "number_of_packages": 200,
                "actual_weight": 10000.0,
                "charged_weight": 11000.0,
                "material_value": 600000.0,
                "declared_value": 600000.0,
                "basic_freight": 12000.0,
                "loading_charge": 800.0,
                "unloading_charge": 800.0,
                "gst_applicable": True,
                "cgst_rate": 9.0,
                "sgst_rate": 9.0,
                "gst_amount": 2160.0,
                "taxable_amount": 12000.0,
                "freight_payment_mode": "to_pay",
                "payment_status": "pending",
                "current_shipment_status": "in_transit",
                "driver_name": "Rakesh Sharma",
                "driver_mobile": "8111111111",
                "driver_license": "MP123456789",
                "helper_name": "Mukesh Jain",
                "trip_number": "TRIP-008",
                "route_code": "RT-IND-BHO",
                "route_name": "Indore-Bhopal Route",
                "origin": "Indore",
                "destination": "Bhopal",
                "via_route": "Indore-Ujjain-Bhopal",
                "freight_collected_from": "Consignee",
                "advance_amount": 5000.0,
                "balance_amount": 7000.0,
                "freight_due": 15760.0,
                "paid_amount": 5000.0,
                "receipt_number": "REC-008",
                "credit_party": "HIJ Supermarket",
                "dispatch_datetime": datetime.now().isoformat(),
                "dispatch_from_branch": "Indore Branch",
                "expected_transit_time": "8 hours",
                "tracking_number": "TRK-008-2024",
                "created_by": "admin",
                "remarks": "Perishable items - expedited delivery required"
            },
            {
                "gr_number": "GR-2024-009",
                "challan_number": "CH-009",
                "party_information": "KLM Auto Parts",
                "consignor_name": "KLM Auto Parts",
                "consignor_address": "345 Auto Zone, Coimbatore",
                "consignor_gstin": "33NOPQRS3456T7U8",
                "consignor_mobile": "9876543226",
                "consignor_email": "klm@autoparts.com",
                "consignee_name": "MNO Garage",
                "consignee_address": "678 Garage Street, Kochi",
                "consignee_gstin": "32TUVWX9012Y9Z0",
                "consignee_mobile": "9876543227",
                "consignor_email": "mno@garage.com",
                "pickup_point": "Coimbatore Factory",
                "pickup_city": "Coimbatore",
                "pickup_state": "Tamil Nadu",
                "pickup_pincode": "641001",
                "delivery_location": "Kochi Workshop",
                "delivery_city": "Kochi",
                "delivery_state": "Kerala",
                "delivery_pincode": "682001",
                "article_description": "Auto Spare Parts - 150 boxes",
                "number_of_packages": 150,
                "actual_weight": 3000.0,
                "charged_weight": 3300.0,
                "material_value": 900000.0,
                "declared_value": 900000.0,
                "basic_freight": 16000.0,
                "loading_charge": 900.0,
                "unloading_charge": 900.0,
                "gst_applicable": True,
                "igst_rate": 18.0,
                "gst_amount": 2880.0,
                "taxable_amount": 16000.0,
                "freight_payment_mode": "to_pay",
                "payment_status": "partial",
                "current_shipment_status": "in_transit",
                "driver_name": "Balasubramanian",
                "driver_mobile": "8000000000",
                "driver_license": "TN987654321",
                "helper_name": "Karthikeyan",
                "trip_number": "TRIP-009",
                "route_code": "RT-COI-KOC",
                "route_name": "Coimbatore-Kochi Route",
                "origin": "Coimbatore",
                "destination": "Kochi",
                "via_route": "Coimbatore-Palakkad-Kochi",
                "freight_collected_from": "Consignee",
                "advance_amount": 8000.0,
                "balance_amount": 8000.0,
                "freight_due": 20680.0,
                "paid_amount": 8000.0,
                "receipt_number": "REC-009",
                "credit_party": "MNO Garage",
                "dispatch_datetime": datetime.now().isoformat(),
                "dispatch_from_branch": "Coimbatore Branch",
                "expected_transit_time": "10 hours",
                "tracking_number": "TRK-009-2024",
                "created_by": "admin",
                "remarks": "Fragile items - careful handling required"
            },
            {
                "gr_number": "GR-2024-010",
                "challan_number": "CH-010",
                "party_information": "PQR Furniture",
                "consignor_name": "PQR Furniture",
                "consignor_address": "901 Furniture Hub, Surat",
                "consignor_gstin": "24ABCDEFG1234H5I6",
                "consignor_mobile": "9876543228",
                "consignor_email": "pqr@furniture.com",
                "consignee_name": "STU Home Decor",
                "consignee_address": "234 Decor Street, Vadodara",
                "consignee_gstin": "24HIJKLM7890N1O2",
                "consignee_mobile": "9876543229",
                "consignee_email": "stu@homedecor.com",
                "pickup_point": "Surat Warehouse",
                "pickup_city": "Surat",
                "pickup_state": "Gujarat",
                "pickup_pincode": "395001",
                "delivery_location": "Vadodara Showroom",
                "delivery_city": "Vadodara",
                "delivery_state": "Gujarat",
                "delivery_pincode": "390001",
                "article_description": "Furniture Items - 50 pieces",
                "number_of_packages": 50,
                "actual_weight": 2500.0,
                "charged_weight": 2750.0,
                "material_value": 750000.0,
                "declared_value": 750000.0,
                "basic_freight": 10000.0,
                "loading_charge": 700.0,
                "unloading_charge": 700.0,
                "gst_applicable": True,
                "cgst_rate": 9.0,
                "sgst_rate": 9.0,
                "gst_amount": 1800.0,
                "taxable_amount": 10000.0,
                "freight_payment_mode": "paid",
                "payment_status": "paid",
                "current_shipment_status": "delivered",
                "driver_name": "Dinesh Patel",
                "driver_mobile": "7999999999",
                "driver_license": "GJ234567890",
                "helper_name": "Jignesh Shah",
                "trip_number": "TRIP-010",
                "route_code": "RT-SUR-VAD",
                "route_name": "Surat-Vadodara Route",
                "origin": "Surat",
                "destination": "Vadodara",
                "via_route": "Surat-Bharuch-Vadodara",
                "freight_collected_from": "Consignor",
                "advance_amount": 0.0,
                "balance_amount": 0.0,
                "freight_due": 0.0,
                "paid_amount": 13200.0,
                "receipt_number": "REC-010",
                "credit_party": "",
                "dispatch_datetime": (datetime.now() - timedelta(days=2)).isoformat(),
                "dispatch_from_branch": "Surat Branch",
                "expected_transit_time": "6 hours",
                "actual_transit_time": "5.5 hours",
                "tracking_number": "TRK-010-2024",
                "delivered_datetime": (datetime.now() - timedelta(hours=47)).isoformat(),
                "delivered_by": "Showroom Manager",
                "received_by_name": "Narendra Patel",
                "received_by_signature": "Narendra P.",
                "seal_number": "SL-010",
                "pod_number": "POD-010",
                "created_by": "admin",
                "remarks": "Bulky items - special loading equipment required"
            }
        ]

        # Create bilty entries
        created_count = 0
        for i, data in enumerate(sample_data, 1):
            # Check if GR number already exists
            if TransportBill.query.filter_by(gr_number=data['gr_number']).first():
                print(f"Skipping {data['gr_number']} - already exists")
                continue

            # Select random location, delivery type, and vehicle
            location = locations[i % len(locations)]
            delivery_type = delivery_types[i % len(delivery_types)]
            vehicle = vehicles[i % len(vehicles)]

            # Extract basic fields
            basic_fields = {
                'gr_number': data['gr_number'],
                'date': datetime.now().date() if i % 2 == 0 else (datetime.now() - timedelta(days=i)).date(),
                'challan_number': data['challan_number'],
                'party_information': data['party_information'],
                'location_id': location.id,
                'rate': location.rate,
                'delivery_type_id': delivery_type.id,
                'vehicle_id': vehicle.id,
                'status': data['current_shipment_status']
            }

            # Store extended data as JSON
            extended_data = {k: v for k, v in data.items() if k not in basic_fields}

            bill = TransportBill(
                tenant_id=tenant.id,
                name=f"BIL-{i:04d}",
                **basic_fields,
                extended_data=json.dumps(extended_data)
            )

            db.session.add(bill)
            created_count += 1

        db.session.commit()
        print(f"Successfully created {created_count} bilty entries!")
        print(f"Total bilty entries in database: {TransportBill.query.count()}")

if __name__ == "__main__":
    create_dummy_bilty()
