"""Add attachment and certificate expiry fields

Revision ID: 365a020b78a6
Revises: b676b2f11a78
Create Date: 2026-04-16 15:30:56.282323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '365a020b78a6'
down_revision = 'b676b2f11a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transport_bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bilty_attachment_1_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('bilty_attachment_2_path', sa.String(length=500), nullable=True))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permit_1_year_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('permit_5_year_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('road_tax_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('puc_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('insurance_attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('fitness_certificate_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('permit_1_year_attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('permit_5_year_attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('road_tax_attachment_path', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('puc_attachment_path', sa.String(length=500), nullable=True))
        batch_op.drop_column('permit_expiry')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permit_expiry', sa.DATE(), nullable=True))
        batch_op.drop_column('puc_attachment_path')
        batch_op.drop_column('road_tax_attachment_path')
        batch_op.drop_column('permit_5_year_attachment_path')
        batch_op.drop_column('permit_1_year_attachment_path')
        batch_op.drop_column('fitness_certificate_path')
        batch_op.drop_column('insurance_attachment_path')
        batch_op.drop_column('puc_expiry')
        batch_op.drop_column('road_tax_expiry')
        batch_op.drop_column('permit_5_year_expiry')
        batch_op.drop_column('permit_1_year_expiry')

    with op.batch_alter_table('transport_bills', schema=None) as batch_op:
        batch_op.drop_column('bilty_attachment_2_path')
        batch_op.drop_column('bilty_attachment_1_path')

    # ### end Alembic commands ###
