"""Auto migration

Revision ID: 8c15808f2a4f
Revises: 4abb0d02bd1c
Create Date: 2026-04-17 00:25:59.745428

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c15808f2a4f'
down_revision = '4abb0d02bd1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.drop_index('ix_vendors_tenant_id')
        batch_op.drop_index('uq_vendor_code_tenant')
        batch_op.drop_index('uq_vendor_gstin_tenant')

    op.drop_table('vendors')
    with op.batch_alter_table('transport_bills', schema=None) as batch_op:
        batch_op.drop_index('gr_number')
        batch_op.drop_index('ix_transport_bills_tenant_id')
        batch_op.drop_index('name')

    op.drop_table('transport_bills')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index('ix_drivers_tenant_id')
        batch_op.drop_index('uq_driver_code_tenant')

    op.drop_table('drivers')
    with op.batch_alter_table('delivery_types', schema=None) as batch_op:
        batch_op.drop_index('ix_delivery_types_tenant_id')
        batch_op.drop_index('uq_delivery_type_tenant')

    op.drop_table('delivery_types')
    with op.batch_alter_table('tenant_permissions', schema=None) as batch_op:
        batch_op.drop_index('ix_tenant_permissions_tenant_id')
        batch_op.drop_index('uq_tenant_module_permission')

    op.drop_table('tenant_permissions')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_tenant_id')
        batch_op.drop_index('name')

    op.drop_table('expenses')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicles_tenant_id')
        batch_op.drop_index('uq_vehicle_registration_tenant')

    op.drop_table('vehicles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')
        batch_op.drop_index('ix_users_tenant_id')
        batch_op.drop_index('username')

    op.drop_table('users')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index('name')
        batch_op.drop_index('slug')

    op.drop_table('tenants')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_locations_tenant_id')
        batch_op.drop_index('uq_location_tenant')

    op.drop_table('locations')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('ix_loans_tenant_id')
        batch_op.drop_index('name')

    op.drop_table('loans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('loan_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('vehicle_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('principal_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('interest_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('tenure_months', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emi_amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('total_payable', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('total_interest', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('lender_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('lender_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('lender_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('lender_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('agent_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('agent_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('loan_date', sa.DATE(), nullable=True),
    sa.Column('disbursement_date', sa.DATE(), nullable=True),
    sa.Column('first_emi_date', sa.DATE(), nullable=True),
    sa.Column('last_emi_date', sa.DATE(), nullable=True),
    sa.Column('down_payment', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('amount_paid', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('balance_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('emis_paid', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('emis_remaining', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('next_emi_due_date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('loan_account_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('document_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('purpose', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('collateral', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('insurance_details', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='loans_ibfk_2'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='loans_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('ix_loans_tenant_id', ['tenant_id'], unique=False)

    op.create_table('locations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('rate', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='locations_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('uq_location_tenant', ['tenant_id', 'location'], unique=False)
        batch_op.create_index('ix_locations_tenant_id', ['tenant_id'], unique=False)

    op.create_table('tenants',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('slug', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('contact_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index('slug', ['slug'], unique=False)
        batch_op.create_index('name', ['name'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=80), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('full_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='users_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=False)
        batch_op.create_index('ix_users_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('email', ['email'], unique=False)

    op.create_table('vehicles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('registration_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('vehicle_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('make', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('model', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('color', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('fuel_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('engine_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('chassis_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('seating_capacity', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('load_capacity_kg', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('owner_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('purchase_date', sa.DATE(), nullable=True),
    sa.Column('insurance_expiry', sa.DATE(), nullable=True),
    sa.Column('fitness_expiry', sa.DATE(), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('permit_1_year_expiry', sa.DATE(), nullable=True),
    sa.Column('permit_5_year_expiry', sa.DATE(), nullable=True),
    sa.Column('road_tax_expiry', sa.DATE(), nullable=True),
    sa.Column('puc_expiry', sa.DATE(), nullable=True),
    sa.Column('insurance_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('fitness_certificate_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('permit_1_year_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('permit_5_year_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('road_tax_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('puc_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='vehicles_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index('uq_vehicle_registration_tenant', ['tenant_id', 'registration_number'], unique=False)
        batch_op.create_index('ix_vehicles_tenant_id', ['tenant_id'], unique=False)

    op.create_table('expenses',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('expense_date', sa.DATE(), nullable=True),
    sa.Column('category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('description', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('vehicle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_method', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('vendor_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('vendor_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('bill_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('receipt_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='expenses_ibfk_2'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='expenses_ibfk_3'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='expenses_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('ix_expenses_tenant_id', ['tenant_id'], unique=False)

    op.create_table('tenant_permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('can_view', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('can_create', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('can_edit', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('can_delete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('can_export', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='tenant_permissions_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tenant_permissions', schema=None) as batch_op:
        batch_op.create_index('uq_tenant_module_permission', ['tenant_id', 'module_name'], unique=False)
        batch_op.create_index('ix_tenant_permissions_tenant_id', ['tenant_id'], unique=False)

    op.create_table('delivery_types',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='delivery_types_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('delivery_types', schema=None) as batch_op:
        batch_op.create_index('uq_delivery_type_tenant', ['tenant_id', 'delivery_type'], unique=False)
        batch_op.create_index('ix_delivery_types_tenant_id', ['tenant_id'], unique=False)

    op.create_table('drivers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('driver_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('father_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('date_of_birth', sa.DATE(), nullable=True),
    sa.Column('gender', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('blood_group', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('nationality', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('marital_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('mobile_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('alternate_mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('emergency_contact_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('emergency_contact_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('emergency_contact_relation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('address_line1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=True),
    sa.Column('address_line2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=300), nullable=True),
    sa.Column('city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pincode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('employee_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('date_of_joining', sa.DATE(), nullable=True),
    sa.Column('designation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('department', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('employment_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('monthly_salary', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('daily_wage', mysql.DECIMAL(precision=8, scale=2), nullable=True),
    sa.Column('total_experience_years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('license_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('license_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('license_issue_date', sa.DATE(), nullable=True),
    sa.Column('license_expiry_date', sa.DATE(), nullable=True),
    sa.Column('license_issuing_authority', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('license_state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('bank_branch', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('account_holder_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('account_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('ifsc_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('account_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('upi_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('photo_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('aadhaar_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('aadhaar_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('pan_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('pan_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('driving_license_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('bank_attachment_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('police_verification_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('medical_certificate_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('reference1_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('reference1_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('reference1_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('reference2_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('reference2_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('reference2_address', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='drivers_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index('uq_driver_code_tenant', ['tenant_id', 'driver_code'], unique=False)
        batch_op.create_index('ix_drivers_tenant_id', ['tenant_id'], unique=False)

    op.create_table('transport_bills',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('vehicle_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('challan_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('party_information', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('location_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delivery_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rate', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('gr_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('gr_date', sa.DATE(), nullable=True),
    sa.Column('branch_booking_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('gr_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('booking_mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('reference_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('consignor_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('consignor_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('consignor_gstin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('consignor_contact_person', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('consignor_mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('consignor_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('consignee_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('consignee_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('consignee_gstin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('consignee_contact_person', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('consignee_mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('consignee_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('bill_to_party', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('ship_to_party', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('pickup_point', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('pickup_date', sa.DATE(), nullable=True),
    sa.Column('pickup_time', mysql.TIME(), nullable=True),
    sa.Column('pickup_branch', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('loaded_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('loading_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pickup_remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('pickup_city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pickup_state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('pickup_pincode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('delivery_location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('expected_delivery_date', sa.DATE(), nullable=True),
    sa.Column('actual_delivery_date', sa.DATE(), nullable=True),
    sa.Column('delivery_city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('delivery_state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('delivery_pincode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('unloading_point', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('delivery_remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('vehicle_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('vehicle_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('vehicle_capacity', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('vehicle_ownership', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('driver_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('driver_mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('driver_license', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('helper_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('trip_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('route_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('route_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('origin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('destination', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('via_route', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('vehicle_reporting_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('vehicle_release_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('article_description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('package_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('number_of_packages', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('packing_mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('actual_weight', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('charged_weight', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('volume_cbm', mysql.DECIMAL(precision=10, scale=3), nullable=True),
    sa.Column('material_value', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('dimensions', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('goods_category', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('nature_of_goods', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('hsn_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('declared_value', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('insurance_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('insurance_value', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('handling_instructions', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('goods_remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('basic_freight', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('loading_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unloading_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('door_pickup_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('door_delivery_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('hamali_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('detention_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('waiting_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('halting_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('toll_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('border_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('fuel_surcharge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('packing_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('weighment_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('permit_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('driver_allowance', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('night_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('rto_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('extra_km_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('extra_weight_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('insurance_charge', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('other_charges', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('discount', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('net_freight', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('gst_applicable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('igst_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('cgst_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sgst_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('taxable_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('gst_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('reverse_charge_applicable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('eway_bill_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('eway_bill_date', sa.DATE(), nullable=True),
    sa.Column('eway_bill_validity', sa.DATE(), nullable=True),
    sa.Column('invoice_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('lr_tax_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('freight_payment_mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('freight_collected_from', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('advance_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('balance_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('freight_due', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('paid_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('payment_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('receipt_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('credit_party', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('collection_notes', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('dispatch_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('dispatch_from_branch', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('reached_hub', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('transshipment_required', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('transshipment_hub', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('intermediate_vehicle_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('expected_transit_time', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('actual_transit_time', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('delay_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('tracking_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('current_shipment_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('delivered_datetime', mysql.DATETIME(), nullable=True),
    sa.Column('delivered_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('received_by_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('received_by_signature', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('seal_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pod_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('pod_upload_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('damage_shortage_report', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('closed_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('closed_date', mysql.DATETIME(), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('modified_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('approved_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('approved_on', mysql.DATETIME(), nullable=True),
    sa.Column('cancelled_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('cancellation_reason', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('branch_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('user_role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('audit_log_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('print_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('export_status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('hazardous_material', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('temperature_controlled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('insurance_claim_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('shortage_damage_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('customer_complaint_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('claim_amount', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('permit_details', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('vehicle_fitness_expiry', sa.DATE(), nullable=True),
    sa.Column('driver_dl_expiry', sa.DATE(), nullable=True),
    sa.Column('rc_book_details', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('gps_link', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('bilty_attachment_1_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('bilty_attachment_2_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.ForeignKeyConstraint(['delivery_type_id'], ['delivery_types.id'], name='transport_bills_ibfk_3'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name='transport_bills_ibfk_2'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='transport_bills_ibfk_4'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name='transport_bills_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transport_bills', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=False)
        batch_op.create_index('ix_transport_bills_tenant_id', ['tenant_id'], unique=False)
        batch_op.create_index('gr_number', ['gr_number'], unique=False)

    op.create_table('vendors',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('vendor_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('vendor_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=False),
    sa.Column('vendor_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('business_nature', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('establishment_date', sa.DATE(), nullable=True),
    sa.Column('website', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('referral_source', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('contact_person', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('designation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('phone_primary', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('phone_secondary', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('alternate_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('fax_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('reg_address_line1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('reg_address_line2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('reg_city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('reg_state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('reg_pincode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('reg_country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('office_address_line1', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('office_address_line2', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('office_city', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('office_state', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('office_pincode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('office_country', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('same_as_registered', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('gstin', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('gst_registration_date', sa.DATE(), nullable=True),
    sa.Column('gst_state_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=2), nullable=True),
    sa.Column('pan_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('tan_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('tin_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('cin_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=True),
    sa.Column('msme_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=True),
    sa.Column('tax_regime', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('is_composition_dealer', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_tds_applicable', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('tds_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('bank_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('bank_branch', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('account_number', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30), nullable=True),
    sa.Column('account_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('ifsc_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11), nullable=True),
    sa.Column('micr_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=9), nullable=True),
    sa.Column('swift_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=11), nullable=True),
    sa.Column('bank_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('upi_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('primary_contact_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('primary_contact_designation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('primary_contact_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('primary_contact_mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('primary_contact_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('secondary_contact_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('secondary_contact_designation', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('secondary_contact_phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('secondary_contact_mobile', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('secondary_contact_email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=True),
    sa.Column('pan_card_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('gst_certificate_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('bank_proof_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('address_proof_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('msme_certificate_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('incorporation_certificate_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('cancelled_cheque_path', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('kyc_status', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('verification_date', sa.DATE(), nullable=True),
    sa.Column('verified_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('compliance_rating', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('background_check_done', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('background_check_date', sa.DATE(), nullable=True),
    sa.Column('trade_reference_1_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('trade_reference_1_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('trade_reference_1_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('trade_reference_2_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('trade_reference_2_contact', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True),
    sa.Column('trade_reference_2_address', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('credit_limit', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('credit_period_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('opening_balance', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('balance_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=3), nullable=True),
    sa.Column('payment_terms', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200), nullable=True),
    sa.Column('supply_type', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('product_categories', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('lead_time_days', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('min_order_value', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('max_order_value', mysql.DECIMAL(precision=12, scale=2), nullable=True),
    sa.Column('delivery_mode', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True),
    sa.Column('created_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('modified_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('approved_by', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('approved_on', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name='vendors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vendors', schema=None) as batch_op:
        batch_op.create_index('uq_vendor_gstin_tenant', ['tenant_id', 'gstin'], unique=False)
        batch_op.create_index('uq_vendor_code_tenant', ['tenant_id', 'vendor_code'], unique=False)
        batch_op.create_index('ix_vendors_tenant_id', ['tenant_id'], unique=False)

    # ### end Alembic commands ###
