"""Add comprehensive tenant profile fields and tenant addresses

Revision ID: c1f2e3d4a5b6
Revises: b3f3f5565e8a
Create Date: 2026-04-26 16:30:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c1f2e3d4a5b6'
down_revision = 'b3f3f5565e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add new columns to tenants table
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('cin_number', mysql.VARCHAR(length=25), nullable=True))
        batch_op.add_column(sa.Column('pan_number', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('gstin', mysql.VARCHAR(length=15), nullable=False))
        batch_op.add_column(sa.Column('business_type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('establishment_date', mysql.DATE(), nullable=True))
        batch_op.add_column(sa.Column('website_url', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('primary_phone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('secondary_contact_person', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('secondary_contact_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('emergency_contact_phone', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('credit_limit', mysql.NUMERIC(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_terms', mysql.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('bank_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_branch', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('account_number', mysql.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('account_type', mysql.VARCHAR(length=20), nullable=True, server_default='Current'))
        batch_op.add_column(sa.Column('ifsc_code', mysql.VARCHAR(length=11), nullable=True))
        batch_op.add_column(sa.Column('micr_code', mysql.VARCHAR(length=9), nullable=True))
        batch_op.add_column(sa.Column('upi_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('gst_certificate_path', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('pan_card_path', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('cin_certificate_path', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('cancelled_cheque_path', mysql.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', mysql.VARCHAR(length=50), nullable=False, server_default='Basic'))
        batch_op.add_column(sa.Column('plan_expiry_date', mysql.DATE(), nullable=True))
        batch_op.add_column(sa.Column('max_users', mysql.INTEGER(), nullable=True, server_default='5'))
        batch_op.add_column(sa.Column('reg_address_line1', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('reg_address_line2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('reg_city', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('reg_state', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('reg_pincode', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('reg_country', mysql.VARCHAR(length=100), nullable=True, server_default='India'))
        batch_op.add_column(sa.Column('billing_address_line1', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_address_line2', mysql.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('billing_city', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_state', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('billing_pincode', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('billing_country', mysql.VARCHAR(length=100), nullable=True, server_default='India'))
        batch_op.add_column(sa.Column('same_as_registered', mysql.TINYINT(), nullable=True, server_default='0'))

    # Create tenant_addresses table
    op.create_table('tenant_addresses',
        sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('tenant_id', mysql.INTEGER(), nullable=False),
        sa.Column('address_type', mysql.VARCHAR(length=50), nullable=False),
        sa.Column('address_line1', mysql.VARCHAR(length=255), nullable=False),
        sa.Column('address_line2', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
        sa.Column('state', mysql.VARCHAR(length=100), nullable=False),
        sa.Column('pincode', mysql.VARCHAR(length=20), nullable=False),
        sa.Column('country', mysql.VARCHAR(length=100), nullable=True, server_default='India'),
        sa.Column('contact_person', mysql.VARCHAR(length=200), nullable=True),
        sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
        sa.Column('email', mysql.VARCHAR(length=150), nullable=True),
        sa.Column('is_primary', mysql.TINYINT(), nullable=True, server_default='0'),
        sa.Column('is_active', mysql.TINYINT(), nullable=True, server_default='1'),
        sa.Column('created_at', mysql.DATETIME(), nullable=True),
        sa.Column('updated_at', mysql.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('tenant_id', 'address_type', name='uq_tenant_address_type')
    )
    op.create_index('ix_tenant_addresses_tenant_id', 'tenant_addresses', ['tenant_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop tenant_addresses table
    op.drop_index('ix_tenant_addresses_tenant_id', table_name='tenant_addresses')
    op.drop_table('tenant_addresses')
    
    # Remove columns from tenants table
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_column('same_as_registered')
        batch_op.drop_column('billing_country')
        batch_op.drop_column('billing_pincode')
        batch_op.drop_column('billing_state')
        batch_op.drop_column('billing_city')
        batch_op.drop_column('billing_address_line2')
        batch_op.drop_column('billing_address_line1')
        batch_op.drop_column('reg_country')
        batch_op.drop_column('reg_pincode')
        batch_op.drop_column('reg_state')
        batch_op.drop_column('reg_city')
        batch_op.drop_column('reg_address_line2')
        batch_op.drop_column('reg_address_line1')
        batch_op.drop_column('max_users')
        batch_op.drop_column('plan_expiry_date')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('cancelled_cheque_path')
        batch_op.drop_column('cin_certificate_path')
        batch_op.drop_column('pan_card_path')
        batch_op.drop_column('gst_certificate_path')
        batch_op.drop_column('upi_id')
        batch_op.drop_column('micr_code')
        batch_op.drop_column('ifsc_code')
        batch_op.drop_column('account_type')
        batch_op.drop_column('account_number')
        batch_op.drop_column('bank_branch')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('payment_terms')
        batch_op.drop_column('credit_limit')
        batch_op.drop_column('emergency_contact_phone')
        batch_op.drop_column('emergency_contact_name')
        batch_op.drop_column('secondary_contact_phone')
        batch_op.drop_column('secondary_contact_person')
        batch_op.drop_column('primary_phone')
        batch_op.drop_column('website_url')
        batch_op.drop_column('establishment_date')
        batch_op.drop_column('business_type')
        batch_op.drop_column('gstin')
        batch_op.drop_column('pan_number')
        batch_op.drop_column('cin_number')
        batch_op.drop_column('updated_at')
    
    # ### end Alembic commands ###
